config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users
  get 'ajax', as: :ajax, to: 'system#ajax'
  get 'stimulus', as: :stimulus, to: 'system#stimulus'
  get 'vue', as: :vue, to: 'system#vue'
  get 'actioncable', as: :actioncable, to: 'system#actioncable'

  root 'system#ajax'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates_presence_of :msg

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    cookies[:current_user_id] ||= User.all.sample.id
    @_current_user ||= User.find(cookies[:current_user_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user ||= current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
        format.js { render "ajax_append" }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:msg, :user_id)
  end
end

app/controllers/system_controller.rb
class SystemController < ApplicationController
  def ajax
    @message = current_user.messages.new
  end

  def stimulus
    @message = current_user.messages.new
  end

  def vue
    @message = current_user.messages.new
  end

  def actioncable
    @message = current_user.messages.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/system_helper.rb
module SystemHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFrontend</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'hello_vue' %>
</head>

<body>
<section class="section">
  <div class="container">
    <h1 class="title">
      Frontend Comparison
    </h1>
    <nav class="tabs" role="navigation" aria-label="main navigation">
      <ul>
        <li class="<%= "is-active" if current_page?(controller: 'system', action: :ajax) %>"><%= link_to "Ajax", :ajax %></li>
        <li class="<%= "is-active" if current_page?(controller: 'system', action: :actioncable) %>"><%= link_to "Action Cable", :actioncable %></li>
        <li class="<%= "is-active" if current_page?(controller: 'system', action: :stimulus) %>"><%= link_to "Stimulus", :stimulus %></li>
        <li class="<%= "is-active" if current_page?(controller: 'system', action: :vue) %>"><%= link_to "Vue", :vue %></li>
      </ul>
    </nav>
    <%= yield %>
  </div>
</section>
</body>
</html>

app/views/messages/_form.html.slim
= form_with model: @message, **(self.respond_to?(:form_options) ? form_options : {}) do |f|
  = f.hidden_field :user_id
  .field.has-addons
    .control.has-icons-left.is-expanded
      = f.text_field :msg, class: "input #{"is-danger" unless @message.errors[:msg].empty?}"
      span.icon.is-small.is-left
        i.fas.fa-user
      - @message.errors[:msg].each do |msg|
        p.help.is-danger = msg
    .control
      = f.submit "Send", class: 'button is-primary'

app/views/messages/_message.html.slim
p.is-wrapped
  span.tag class="#{"is-info" if message.user == current_user}" = message.user.email
  = message.msg

app/views/messages/ajax_append.js.erb
document.querySelector("#ajax-chat").innerHTML += '<%= escape_javascript render(@message) %>'
document.querySelector("#message_msg").value = ''

app/views/messages/edit.html.slim
h1 Editing message

== render 'form'

=> link_to 'Show', @message
'|
=< link_to 'Back', messages_path

app/views/messages/index.html.slim
h1 Listing messages

table
  thead
    tr
      th Msg
      th User
      th
      th
      th

  tbody
    - @messages.each do |message|
      tr
        td = message.msg
        td = message.user
        td = link_to 'Show', message
        td = link_to 'Edit', edit_message_path(message)
        td = link_to 'Destroy', message, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Message', new_message_path

app/views/messages/new.html.slim
h1 New message

== render 'form'

= link_to 'Back', messages_path

app/views/messages/new.js.erb
document.querySelector("form").outerHTML = '<%= escape_javascript render("form") %>'

app/views/messages/show.html.slim
p#notice = notice

p
  strong Msg:
  = @message.msg
p
  strong User:
  = @message.user

=> link_to 'Edit', edit_message_path(@message)
'|
=< link_to 'Back', messages_path

app/views/system/actioncable.html.slim
a.button href="https://guides.rubyonrails.org/action_cable_overview.html" target="_blank"
  i.fa.fa-book
  | Action Cable

hr
.level
  .level-left.is-block
    h3.subtitle Users in Chat
    ul.list.is-hoverable
      - User.all.each do |user|
        li.list-item
          = user.email
          - if user == current_user
            span.tag.is-dark.is-light YOU

  .level-right style="padding: 2rem; max-width: 80%;"
    .panel.container
      .panel-heading Chat
      .panel-block.is-block#actioncable-chat
        - Message.all.each do |message|
          p.is-wrapped
            span.tag class="#{"is-info" if message.user == current_user}" = message.user.email
            = message.msg
      .panel-block
        .container
          = render 'messages/form', form_options: {id: "actioncable-form"}

app/views/system/ajax.html.slim
a.button href="https://guides.rubyonrails.org/working_with_javascript_in_rails.html" target="_blank"
  i.fa.fa-book
  | Ajax Dokumentation

hr
.level
  .level-left.is-block
    h3.subtitle Users in Chat
    ul.list.is-hoverable
      - User.all.each do |user|
        li.list-item
          = user.email
          - if user == current_user
            span.tag.is-dark.is-light YOU

  .level-right style="padding: 2rem; max-width: 80%;"
    .panel.container
      .panel-heading Chat
      .panel-block.is-block#ajax-chat
        = render Message.all
      .panel-block
        .container
          = render 'messages/form', form_options: {remote: true}

app/views/system/stimulus.html.slim
a.button href="https://stimulusjs.org/" target="_blank"
  i.fa.fa-book
  | Stimulus Dokumentation

hr
.level
  .level-left.is-block
    h3.subtitle Users in Chat
    ul.list.is-hoverable
      - User.all.each do |user|
        li.list-item
          = user.email
          - if user == current_user
            span.tag.is-dark.is-light YOU

  .level-right style="padding: 2rem; max-width: 80%;"
    .panel.container data-controller="chat"
      .panel-heading Chat
      .panel-block.is-block#ajax-chat
        - Message.all.each do |message|
          p.is-wrapped
            span.tag class="#{"is-info" if message.user == current_user}" = message.user.email
            = message.msg
      .panel-block
        .container
          = render 'messages/form', form_options: {data: {action: "submit->chat#speak"}}

app/views/system/vue.html.slim
app#vue-chat json-users=User.all.to_json current-user-id=current_user.id json-messages=Message.all.to_json(include: :user)

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path